import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { rinsideCompressed, rinsideNarrow } from "@/fonts";
import "../../styles/globals.scss";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "no" }];
}

export default async function LocaleLayout({
  children,
  params,
  navbar,
  footer,
}: {
  children: React.ReactNode;
  params: { locale: string };
  navbar: React.ReactNode;
  footer: React.ReactNode;
}) {
  // Await the params to ensure locale is available
  const { locale } = await Promise.resolve(params);

  return (
    <html lang={locale} className="h-full">
      <body
        className={`${rinsideCompressed.variable} ${rinsideNarrow.variable} antialiased ${inter.className} flex min-h-full flex-col`}
      >
        {/* Navbar Section */}
        {navbar}

        {/* Main Content */}
        <main className="flex-1">{children}</main>

        {/* Footer Section */}
        {footer}
      </body>
    </html>
  );
}
