import type { Metadata } from "next";
import "./globals.css";
import { getLocale } from "next-intl/server";
import { font1, font2 } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "no" }];
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  return (
    <html lang={locale}>
      <body className={`${font1.variable} ${font2.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
